version: '3'
services:
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    - "3306:3306"
    volumes:
    - ./data:/var/lib/mysql
    - ./logs:/var/log
    - ./my.cnf:/etc/my.cnf
