version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 'devdev'
      POSTGRES_PASSWORD: 'asdf23'
    ports:
    - "5432:5432"
    volumes:
    - ./data:/var/lib/postgresql/data
